version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    versioning-strategy: increase
    ignore:
      - dependency-name: "phpunit/phpunit"
        update-types: ["version-update:semver-major"]
