sonar.projectKey=sirosoft_siro-core
sonar.organization=sirosoft
sonar.host.url=https://sonarcloud.io

sonar.projectName=Siro Core
sonar.projectVersion=0.26.0
sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=vendor/**,tests/**,scripts/**,storage/**,docs/**,coverage/**,**.phpdoc/**,**.phpunit.cache/**

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.testExecutionReportPaths=coverage/junit.xml
sonar.tests=tests

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
