<?php

declare(strict_types=1);

namespace Siro\Core\Commands;

final class MakeApiCommand
{
    use CommandSupport;

    public function __construct(private readonly string $basePath)
    {
    }

    /** @param array<int, string> $args */
    public function run(array $args): int
    {
        $resource = strtolower(trim((string) ($args[0] ?? '')));
        if ($resource === '') {
            $this->write('Resource name is required. Example: php siro make:api users');
            return 1;
        }

        $resource = preg_replace('/[^a-z0-9_]+/', '_', $resource) ?? $resource;
        $resource = trim($resource, '_');
        if ($resource === '') {
            $this->write('Invalid resource name.');
            return 1;
        }

        $model = $this->studly($this->singular($resource));
        $controllerClass = $model . 'Controller';
        $resourceClass = $model . 'Resource';

        $controllerPath = $this->basePath . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'Controllers' . DIRECTORY_SEPARATOR . $controllerClass . '.php';
        $resourcePath = $this->basePath . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'Resources' . DIRECTORY_SEPARATOR . $resourceClass . '.php';
        $routeFile = $this->basePath . DIRECTORY_SEPARATOR . 'routes' . DIRECTORY_SEPARATOR . 'api.php';

        if (!is_dir(dirname($controllerPath))) {
            mkdir(dirname($controllerPath), 0775, true);
        }
        if (!is_dir(dirname($resourcePath))) {
            mkdir(dirname($resourcePath), 0775, true);
        }

        if (!is_file($controllerPath) || $this->confirmOverwrite($this->basePath, $controllerPath)) {
            file_put_contents($controllerPath, $this->controllerTemplate($controllerClass, $resourceClass, $resource, $model));
            $this->write('Generated: app/Controllers/' . $controllerClass . '.php');
        } else {
            $this->write('Skipped: app/Controllers/' . $controllerClass . '.php');
        }

        if (!is_file($resourcePath) || $this->confirmOverwrite($this->basePath, $resourcePath)) {
            file_put_contents($resourcePath, $this->resourceTemplate($resourceClass));
            $this->write('Generated: app/Resources/' . $resourceClass . '.php');
        } else {
            $this->write('Skipped: app/Resources/' . $resourceClass . '.php');
        }

        $routesSource = is_file($routeFile) ? (string) file_get_contents($routeFile) : "<?php\n\ndeclare(strict_types=1);\n\n";
        $routeMarker = "Generated by: php siro make:api {$resource}";
        if (!str_contains($routesSource, $routeMarker)) {
            $newContent = rtrim($routesSource) . "\n\n" . $this->routeTemplate($resource, $controllerClass) . "\n";
            file_put_contents($routeFile, $newContent);
            $this->write('Updated: routes/api.php');
        } else {
            $this->write('Routes already exist for ' . $resource . '. Skipped route generation.');
        }

        return 0;
    }

    private function controllerTemplate(string $class, string $resourceClass, string $resource, string $model): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace App\Controllers;

use App\Models\{$model};
use App\Resources\{$resourceClass};
use Siro\Core\Request;
use Siro\Core\Response;

final class {$class}
{
    public function index(Request \$request): Response
    {
        \$perPage = \$request->queryInt('per_page', 20);
        \$page = \$request->queryInt('page', 1);

        \$result = {$model}::query()
            ->select(['id', 'name', 'created_at'])
            ->orderBy('id', 'DESC')
            ->cache(60)
            ->paginate(\$perPage, \$page);

        return Response::paginated(
            {$resourceClass}::collection(\$result['data']),
            \$result['meta'],
            '{$model} list fetched'
        );
    }

    public function show(Request \$request): Response
    {
        \$id = \$request->int('id', 0);
        if (\$id <= 0) {
            return Response::error('Invalid id', 422, ['id' => ['Id must be a positive integer']]);
        }

        \$item = {$model}::find(\$id);

        if (\$item === null) {
            return Response::error('{$model} not found', 404);
        }

        return Response::success((new {$resourceClass}(\$item->toArray()))->toArray(), '{$model} fetched');
    }

    public function store(Request \$request): Response
    {
        \$validated = \$request->validate([
            'name' => 'required|min:3|max:120',
        ]);

        \$item = {$model}::create([
            'name' => \$validated['name'],
            'created_at' => date('Y-m-d H:i:s'),
        ]);

        return Response::created(['id' => \$item->id], '{$model} created');
    }

    public function update(Request \$request): Response
    {
        \$id = \$request->int('id', 0);
        if (\$id <= 0) {
            return Response::error('Invalid id', 422, ['id' => ['Id must be a positive integer']]);
        }

        \$validated = \$request->validate([
            'name' => 'min:3|max:120',
        ]);

        \$item = {$model}::find(\$id);
        if (\$item === null) {
            return Response::error('{$model} not found', 404);
        }

        \$item->update(\$validated);

        return Response::success(null, '{$model} updated');
    }

    public function delete(Request \$request): Response
    {
        \$id = \$request->int('id', 0);
        if (\$id <= 0) {
            return Response::error('Invalid id', 422, ['id' => ['Id must be a positive integer']]);
        }

        \$item = {$model}::find(\$id);
        if (\$item === null) {
            return Response::error('{$model} not found', 404);
        }

        \$item->delete();

        return Response::success(null, '{$model} deleted');
    }
}

PHP;
    }

    private function resourceTemplate(string $class): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace App\Resources;

use Siro\Core\Resource;

final class {$class} extends Resource
{
    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => \$this->data['id'] ?? null,
            'name' => \$this->data['name'] ?? null,
            'created_at' => \$this->data['created_at'] ?? null,
        ];
    }
}

PHP;
    }

    private function routeTemplate(string $resource, string $controllerClass): string
    {
        return str_replace(
            ['{{resource}}', '{{controller}}'],
            [$resource, $controllerClass],
            <<<'PHP'
// Generated by: php siro make:api {{resource}}
$app->router->get('/{{resource}}', [\App\Controllers\{{controller}}::class, 'index']);
$app->router->get('/{{resource}}/{id}', [\App\Controllers\{{controller}}::class, 'show']);
$app->router->post('/{{resource}}', [\App\Controllers\{{controller}}::class, 'store']);
$app->router->put('/{{resource}}/{id}', [\App\Controllers\{{controller}}::class, 'update']);
$app->router->delete('/{{resource}}/{id}', [\App\Controllers\{{controller}}::class, 'delete']);
PHP
        );
    }
}
