<?php

declare(strict_types=1);

/**
 * DAST Report Generator
 *
 * Parses PHPUnit DAST test output and produces a readable security report.
 * Usage: php scripts/dast-report.php [--input=results.xml] [--output=report.md]
 */

$inputFile = 'dast-results.xml';
$outputFile = 'php://stdout';

foreach ($argv as $i => $arg) {
    if ($i === 0) continue;
    if (str_starts_with($arg, '--input=')) {
        $inputFile = substr($arg, 8);
    } elseif (str_starts_with($arg, '--output=')) {
        $outputFile = substr($arg, 9);
    }
}

if (!is_file($inputFile)) {
    fwrite(STDERR, "Input file not found: $inputFile\n");
    fwrite(STDERR, "Usage: php scripts/dast-report.php --input=dast-results.xml --output=report.md\n");
    exit(1);
}

$xml = simplexml_load_file($inputFile);
if ($xml === false) {
    fwrite(STDERR, "Failed to parse XML: $inputFile\n");
    exit(1);
}

$report = [];
$report['generated_at'] = date('Y-m-d H:i:s T');
$report['testsuite'] = [
    'name' => (string) $xml['name'],
    'tests' => (int) $xml['tests'],
    'assertions' => (int) $xml['assertions'],
    'errors' => (int) $xml['errors'],
    'failures' => (int) $xml['failures'],
    'skipped' => (int) $xml['skipped'],
    'time' => (float) $xml['time'],
];

$report['failures'] = [];
foreach ($xml->xpath('//testcase[failure]') as $failure) {
    $report['failures'][] = [
        'class' => (string) $failure['class'],
        'method' => (string) $failure['name'],
        'message' => (string) $failure->failure['message'],
        'type' => (string) $failure->failure['type'],
    ];
}

$report['errors'] = [];
foreach ($xml->xpath('//testcase[error]') as $error) {
    $report['errors'][] = [
        'class' => (string) $error['class'],
        'method' => (string) $error['name'],
        'message' => (string) $error->error['message'],
    ];
}

$output = '';
$output .= "# DAST Security Scan Report\n\n";
$output .= "**Generated:** {$report['generated_at']}\n\n";
$output .= "## Summary\n\n";
$output .= "- Tests: {$report['testsuite']['tests']}\n";
$output .= "- Assertions: {$report['testsuite']['assertions']}\n";
$output .= "- Errors: {$report['testsuite']['errors']}\n";
$output .= "- Failures: {$report['testsuite']['failures']}\n";
$output .= "- Skipped: {$report['testsuite']['skipped']}\n";
$output .= "- Duration: {$report['testsuite']['time']}s\n\n";

if ($report['failures'] !== []) {
    $output .= "## Failures\n\n";
    foreach ($report['failures'] as $f) {
        $output .= "### {$f['class']}::{$f['method']}\n";
        $output .= "- **Message:** {$f['message']}\n";
        $output .= "- **Type:** {$f['type']}\n\n";
    }
}

if ($report['errors'] !== []) {
    $output .= "## Errors\n\n";
    foreach ($report['errors'] as $e) {
        $output .= "### {$e['class']}::{$e['method']}\n";
        $output .= "- **Message:** {$e['message']}\n\n";
    }
}

$output .= "## Security Categories Covered\n\n";
$output .= "- SQL Injection (path-based)\n";
$output .= "- Cross-Site Scripting (XSS) in URLs\n";
$output .= "- Path Traversal\n";
$output .= "- HTTP Method Fuzzing\n";
$output .= "- Header Injection / Malformed Headers\n";

$output .= "\n---\n*Report generated by SiroSoft DAST Scanner*\n";

if ($outputFile === 'php://stdout' || $outputFile === 'php://output') {
    echo $output;
} else {
    file_put_contents($outputFile, $output);
    echo "Report written to: $outputFile\n";
}
